"""Phase 9.0 and 9.7 - one fixed run of the player, measured frame by frame.

Scratch, like `engine_spike.py`: nothing in `tdpy` imports it. The same
recorder takes the 9.0 baseline from today's single-process build and the 9.7
measurement from the Engine COMP build, so the two numbers come from one
instrument.

Run from the textport, **straight after pressing rebuild**, so the run starts
from the first clip with nothing cued:

    import spikes.baseline as b; b.start()

It writes the cycle's settings, deals seed `SEED`, presses play, and records
until `minutes` have passed. Then it stops itself and writes
`logs/baseline-<label>-<time>.csv` (one row a second) and a summary line to
`logs/startup.log`. `b.stop()` ends a run early and still writes both.

**Random cue is off for the run.** `player.cue_fraction` draws from an
unseeded generator, so a run with it on could not be repeated, and a
comparison between two unrepeatable runs measures the draw as much as the
build.

**What is counted, and from where.** Host frames dropped come from a Perform
CHOP's `droppedframes`, which the help defines as the frames dropped between
the last frame and this one, so it is summed. Each player's `pre_read_misses`
comes from its Info CHOP; whether that counter is cumulative or resets per file
is not documented, so the recorder sums its *increases* and also writes the raw
value each second, and the CSV settles which it is.

For 9.7, pass `sources` naming the engine's Info CHOP channels instead of the
players' - `engine_dropped_frames` and `engine_read_ahead_misses` - since the
players will be in another process.
"""

import csv
import time

from tdpy import startup

PARENT = "/project1"
PERFORM = "baselinePerform"
EXECUTE = "baselineExec"
TAG = "[baseline]"

SEED = 419273
MINUTES = 5.0

#: Perform CHOP channels the recorder reads, switched on explicitly rather than
#: trusted to the defaults. Names are the parameter names on the type stub at
#: `bin/Lib/tdi/ops/chops/performCHOP.py`; that the channels carry the same
#: names is an assumption, and `_read` says so once if it is wrong.
PERFORM_CHANNELS = ("fps", "msec", "droppedframes")


def _tdpy():
    """The project modules, imported now rather than at module scope.

    The rebuild button runs `startup.reload()`, which drops every `tdpy`
    submodule. A reference taken when this file was first imported would then
    point at the old `player`, whose seed is not the one the new network reads -
    so a second run after a rebuild would deal a deck nothing is playing.
    """
    from tdpy import build, player, settings

    return build, player, settings


def run_settings():
    """The cycle for a measured run.

    A four-second dwell with a fifth of it spent fading cuts fifteen times a
    minute and keeps both players busy - the condition the stutter was
    reported under.
    """
    _, _, settings = _tdpy()
    return {
        settings.DWELL_ON: True,
        settings.DWELL: 4.0,
        settings.FADE: 0.2,
        settings.RANDOM_CUE: False,
        settings.ADVANCE_ON_END: True,
    }

EXECUTE_TEXT = '''# Generated by spikes/baseline.py - edits here are overwritten.
def onFrameEnd(frame):
    import spikes.baseline
    spikes.baseline.on_frame(frame)
    return
'''

#: The run in progress, or None. Module state because the recorder is called
#: once a frame from a DAT and has nowhere else to keep a running total.
RUN = None


def player_sources():
    """(label, CHOP path, channel) for each player's pre-read misses and buffer."""
    build, _, _ = _tdpy()
    container = f"{build.BUILD_PARENT}/{build.BUILD_ROOT}"
    sources = []
    for top, info in zip(build.PLAYER_TOPS, build.PLAYER_INFO_CHOPS):
        sources.append((f"{top}_misses", f"{container}/{info}", "pre_read_misses"))
        sources.append((f"{top}_buffer", f"{container}/{info}", "num_pre_read_frames"))
    return sources


def start(label="single", seed=SEED, minutes=MINUTES, sources=None):
    """Configure the player, begin recording, and press play."""
    import td

    global RUN
    stop(write=False)
    _, player, settings = _tdpy()
    parent = td.op(PARENT)
    configuration = run_settings()

    comp = settings.comp()
    for name, value in configuration.items():
        found = settings.parameter(comp, name)
        if found is not None:
            found.val = value

    perform = startup.create(parent, td.performCHOP, PERFORM)
    perform.nodeX, perform.nodeY = -500, -600
    for channel in PERFORM_CHANNELS:
        startup.set_par(perform, channel, True)

    RUN = {
        "label": label,
        "seed": seed,
        "until": time.monotonic() + minutes * 60.0,
        "started": time.monotonic(),
        "sources": list(player_sources() if sources is None else sources),
        "frames": 0,
        "dropped": 0,
        "frames_with_drops": 0,
        "fps_min": None,
        "msec_max": 0.0,
        "increases": {},
        "last": {},
        "rows": [],
        "next_row": time.monotonic(),
        "missing": set(),
    }

    player.set_seed(seed)
    player.play()

    execute = startup.create(parent, td.executeDAT, EXECUTE)
    execute.nodeX, execute.nodeY = -500, -750
    execute.text = EXECUTE_TEXT
    startup.set_par(execute, "frameend", True)

    startup.report(
        f"{TAG} {label}: seed {seed}, {minutes:g} min, settings {configuration}"
    )


def _read(path, channel):
    """A channel's value, or None - reported once per run, not once a frame."""
    import td

    chop = td.op(path)
    found = chop[channel] if chop is not None else None
    if found is None:
        key = (path, channel)
        if key not in RUN["missing"]:
            RUN["missing"].add(key)
            startup.report(f"{TAG} no {channel} on {path}")
        return None
    return found.eval()


def on_frame(frame):
    """Accumulate one frame. Called by the Execute DAT."""
    if RUN is None:
        return
    perform = f"{PARENT}/{PERFORM}"
    dropped = _read(perform, "droppedframes") or 0
    fps = _read(perform, "fps")
    msec = _read(perform, "msec") or 0.0

    RUN["frames"] += 1
    RUN["dropped"] += int(dropped)
    RUN["frames_with_drops"] += 1 if dropped else 0
    if fps is not None and RUN["frames"] > 60:
        # The first second is the Perform CHOP filling its window, not the run.
        RUN["fps_min"] = fps if RUN["fps_min"] is None else min(RUN["fps_min"], fps)
    RUN["msec_max"] = max(RUN["msec_max"], msec)

    values = {}
    for label, path, channel in RUN["sources"]:
        value = _read(path, channel)
        values[label] = value
        previous = RUN["last"].get(label)
        if value is not None and previous is not None and value > previous:
            RUN["increases"][label] = RUN["increases"].get(label, 0) + (value - previous)
        RUN["last"][label] = value

    now = time.monotonic()
    if now >= RUN["next_row"]:
        RUN["next_row"] += 1.0
        RUN["rows"].append(
            {"seconds": round(now - RUN["started"], 1), "fps": fps,
             "dropped_total": RUN["dropped"], **values}
        )
    if now >= RUN["until"]:
        stop()


def stop(write=True):
    """End the run, remove the recorder, and write the CSV and summary."""
    import td

    global RUN
    parent = td.op(PARENT)
    for name in (EXECUTE, PERFORM):
        found = parent.op(name) if parent is not None else None
        if found is not None:
            found.destroy()
    if RUN is None:
        return None
    run, RUN = RUN, None
    if not write:
        return None

    stamp = time.strftime("%Y%m%d-%H%M%S")
    path = startup.project_root() / "logs" / f"baseline-{run['label']}-{stamp}.csv"
    path.parent.mkdir(exist_ok=True)
    if run["rows"]:
        with open(path, "w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(run["rows"][0]))
            writer.writeheader()
            writer.writerows(run["rows"])

    seconds = time.monotonic() - run["started"]
    summary = (
        f"{TAG} {run['label']} seed {run['seed']}: {seconds:.0f}s, {run['frames']} frames,"
        f" {run['dropped']} dropped over {run['frames_with_drops']} frames,"
        f" fps min {run['fps_min']}, frame msec max {run['msec_max']:.1f},"
        f" increases {run['increases']} - {path.name}"
    )
    startup.report(summary)
    return summary
