"""Phase 9.1 - the Engine COMP spikes, as one generated component.

Scratch, not project code: nothing in `tdpy` imports this, and `remove()`
takes away everything `setup()` made. It exists to answer the five questions on
160.0020 before `tdpy/link.py` and the real bootstrap are written, since each
answer can change them.

Run from the textport, with the project open:

    import spikes.engine_spike as s; s.setup()

`setup()` builds a Base COMP holding a bootstrap, saves it as a .tox under
`spikes/out/` (git-ignored), destroys the source so none of it runs in the
host, and loads the .tox into an Engine COMP. Then:

    s.status()                                  # engine state and host fps
    s.tap()                                     # once loaded: wire the outputs
    op('/project1/engineSpike').par.Counter = 7 # control: a value parameter
    op('/project1/engineSpike').par.Ping.pulse()# spike 1: does a pulse cross?
    op('/project1/engineSpike').par.reload.pulse()  # spike 3: modules kept?
    op('/project1/engineSpike').par.Raise.pulse()   # spike 4: engine exception
    op('/project1/engineSpike').par.Stall = 1       # spike 5: slow engine frame
    s.remove()

Spike 2 (`project.folder`, the working directory) and the rest of spike 4
(where prints go) answer themselves in `logs/engine_spike.log` on load. Every
line the engine writes is tagged `[engine]` and carries its process id, so a
line in the host's textport can be told apart from one in the log.

**The Counter parameter is the control for the Ping pulse.** The help says
custom parameters cross host to engine; if Counter arrives and Ping does not,
the finding is about pulses. If neither arrives, it is about this spike.

Every operator and parameter name here was read off the type stubs under
`bin/Lib/tdi/ops/` and the callback signatures off
`bin/Lib/tdutils/DATScripts/`. Menu choices go through `startup.set_menu`,
which reports the real tokens if a label is wrong.
"""

import os
import pathlib
import time

from tdpy import startup

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "spikes" / "out"
TOX = OUT / "engine_spike.tox"
ENGINE_LOG = ROOT / "logs" / "engine_spike.log"

PARENT = "/project1"
SOURCE = "engineSpikeSource"
ENGINE = "engineSpike"
STATUS_INFO = "engineSpikeStatus"
PERFORM_INFO = "engineSpikePerform"
HOST_PERFORM = "engineSpikeHostPerform"
STATE_TAP = "engineSpikeState"
VIDEO_TAP = "engineSpikeVideo"
MADE = (ENGINE, STATUS_INFO, PERFORM_INFO, HOST_PERFORM, STATE_TAP, VIDEO_TAP, SOURCE)

TAG = "[spike host]"

#: The bootstrap. Plain text with one placeholder rather than an f-string or
#: `.format`, because it is Python full of braces itself.
#:
#: Each probe is wrapped so that one failing - `project` not existing inside
#: the engine, say - is written down and the others still run. That is a
#: report, not a fallback: nothing downstream uses a substituted value.
BOOTSTRAP = '''# Generated by spikes/engine_spike.py - edits here are overwritten.
import os
import sys
import time
import traceback

REPO = __REPO__
LOG = os.path.join(REPO, "logs", "engine_spike.log")


def _log(message):
    line = f"[{time.strftime('%H:%M:%S')}] [engine pid {os.getpid()}] {message}"
    print(line)
    try:
        with open(LOG, "a", encoding="utf-8") as handle:
            handle.write(line + "\\n")
    except OSError as error:
        print(f"[engine] could not write {LOG}: {error}")


def _probe(label, read):
    try:
        _log(f"{label} = {read()!r}")
    except Exception:
        _log(f"{label} RAISED\\n{traceback.format_exc()}")


def onStart():
    _log("onStart ran - the help says it never does under TouchEngine")
    return


def onCreate():
    _log("onCreate")
    _probe("project.folder", lambda: project.folder)
    _probe("project.name", lambda: project.name)
    _probe("os.getcwd()", os.getcwd)
    _probe("me.parent().path", lambda: me.parent().path)
    _probe("repo on sys.path before insert", lambda: REPO in sys.path)
    _probe(
        "marker in sys.modules before import",
        lambda: "spikes.engine_marker" in sys.modules,
    )
    if REPO not in sys.path:
        sys.path.insert(0, REPO)
    try:
        import spikes.engine_marker as marker

        marker.LOADS += 1
        _log(
            f"marker {marker.__file__} imported at {marker.IMPORTED_AT},"
            f" onCreate count {marker.LOADS}"
        )
        import tdpy.startup

        tdpy.startup.report(f"[engine pid {os.getpid()}] reached startup.log")
    except Exception:
        _log(f"import RAISED\\n{traceback.format_exc()}")
    return


SEEN = {}


def onFrameStart(frame):
    top = me.parent()
    stall = top.par.Stall.eval()
    # Once on the first frame, and again whenever the value changes. Silence
    # here means the callback does not fire inside a TouchEngine component;
    # a line reading Stall = 0 after the host has written 1 means the write
    # does not cross. Without it, both look identical from the host.
    if SEEN.get("stall") != stall:
        SEEN["stall"] = stall
        _log(f"onFrameStart frame {frame}: Stall = {stall!r}")
    if stall:
        time.sleep(top.par.Stallms.eval() / 1000.0)
    return
'''

#: The Parameter Execute DAT watching the component's own custom parameters.
#: The Constant CHOP it writes is inside the component, so writing it is not
#: the host-bound parameter write the help rules out.
WATCHER = '''# Generated by spikes/engine_spike.py - edits here are overwritten.
import os


def onPulse(par):
    print(f"[engine pid {os.getpid()}] onPulse {par.name}")
    if par.name == "Ping":
        state = op("state_values")
        state.par.const0value = state.par.const0value.eval() + 1
    elif par.name == "Raise":
        raise RuntimeError("spike 4: deliberate exception inside the engine")
    return


def onValueChange(par, prev):
    print(f"[engine pid {os.getpid()}] onValueChange {par.name} {prev} -> {par.eval()}")
    if par.name == "Counter":
        op("state_values").par.const1value = par.eval()
    return
'''

#: Channels on the state output, in Constant CHOP block order.
STATE_CHANNELS = ("pings", "counter", "engine_frame")

#: The Engine COMP's Info CHOP channels worth reading, from `Engine_COMP.htm`.
STATUS_CHANNELS = (
    "engine_running", "engine_error", "component_loaded", "component_error",
    "initialize_fail", "ready", "running", "crash_reload_count",
)
PERFORM_CHANNELS = (
    "engine_fps", "engine_frame_msec", "engine_dropped_frames",
    "engine_read_ahead_misses", "output_did_wait",
)


def _build_source(parent, td):
    """The component that becomes the .tox, with its bootstrap and outputs."""
    source = startup.create(parent, td.baseCOMP, SOURCE)
    for kind, name, attributes in (
        ("pulse", "Ping", {}),
        ("pulse", "Raise", {}),
        ("int", "Counter", {"default": 0}),
        ("toggle", "Stall", {"default": False}),
        ("float", "Stallms", {"default": 100.0, "min": 0.0, "normMax": 500.0}),
    ):
        par, created = startup.custom_par(source, "Spike", kind, name, **attributes)
        # `default` is an attribute, not a value: Stallms sat at 0 with a
        # default of 100 and the stall slept for nothing. custom_par refuses
        # `val` and hands back `created` so the caller seeds it.
        if created and "default" in attributes:
            par.val = attributes["default"]

    state = startup.create(source, td.constantCHOP, "state_values")
    state.seq.const.numBlocks = max(state.seq.const.numBlocks, len(STATE_CHANNELS))
    for index, channel in enumerate(STATE_CHANNELS):
        startup.set_par(state, f"const{index}name", channel)
        startup.set_par(state, f"const{index}value", 0)
    getattr(state.par, f"const{STATE_CHANNELS.index('engine_frame')}value").expr = (
        "absTime.frame"
    )
    state_out = startup.create(source, td.outCHOP, "state")
    state_out.inputConnectors[0].connect(state)
    # Labelled so `tap()` can show whether an Engine COMP connector's
    # description carries it - the host needs some way to tell its outputs
    # apart, and `connectorder` is "Help Not Available" in the stub.
    startup.set_par(state_out, "label", "spike state")

    label = startup.create(source, td.textTOP, "label")
    label.par.text.expr = (
        "f\"pings {int(op('state_values')['pings'].eval())}"
        " frame {absTime.frame}\""
    )
    video_out = startup.create(source, td.outTOP, "video")
    video_out.inputConnectors[0].connect(label)
    startup.set_par(video_out, "label", "spike video")

    bootstrap = startup.create(source, td.executeDAT, "bootstrap")
    bootstrap.text = BOOTSTRAP.replace("__REPO__", repr(str(ROOT)))
    for flag in ("start", "create", "framestart"):
        startup.set_par(bootstrap, flag, True)

    watcher = startup.create(source, td.parameterexecuteDAT, "watcher")
    watcher.text = WATCHER
    startup.set_par(watcher, "op", "..")
    startup.set_par(watcher, "pars", "Ping Raise Counter")
    for flag in ("custom", "onpulse", "valuechange"):
        startup.set_par(watcher, flag, True)
    return source


def setup():
    """Generate, save and load the spike component. Returns the Engine COMP."""
    import td

    remove()
    parent = td.op(PARENT)
    startup.report(f"{TAG} host pid {os.getpid()}, project.folder {td.project.folder}")

    source = _build_source(parent, td)
    saved = source.save(str(TOX), createFolders=True)
    startup.report(f"{TAG} saved {saved}")
    # Destroyed at once, so the bootstrap's frame callback and the watcher run
    # only in the engine. A host-side copy answering a pulse would pass spike 1
    # for the wrong reason.
    source.destroy()

    engine = startup.create(parent, td.engineCOMP, ENGINE)
    engine.nodeX, engine.nodeY = 0, -600
    startup.set_menu(engine, "clock", "synced")
    startup.set_par(engine, "file", str(TOX))

    for name, info_type in ((STATUS_INFO, "TouchEngine Status"),
                            (PERFORM_INFO, "TouchEngine Perform")):
        info = startup.create(parent, td.infoCHOP, name)
        startup.set_par(info, "op", engine.path)
        startup.set_menu(info, "infotype", info_type)
    startup.create(parent, td.performCHOP, HOST_PERFORM)

    startup.report(
        f"{TAG} engine at {engine.path} loading {TOX.name} -"
        f" engine lines go to {ENGINE_LOG}"
    )
    return engine


def tap():
    """Wire a Null CHOP and a Null TOP onto the Engine COMP's outputs.

    Run once the engine reports `component_loaded`, since the connectors come
    from the loaded .tox. Which connector is the CHOP and which the TOP is not
    documented, and `Connector.outOP` names an Out operator that lives in the
    other process - so each connector is described, tried with each Null, and
    the result reported. Nothing is assumed about the order.
    """
    import td

    parent = td.op(PARENT)
    engine = parent.op(ENGINE)
    if engine is None:
        startup.report(f"{TAG} no {ENGINE} - run setup() first")
        return
    lines = [f"{TAG} {len(engine.outputConnectors)} output connector(s)"]
    for connector in engine.outputConnectors:
        lines.append(f"  [{connector.index}] {connector.description!r}")

    for name, optype in ((STATE_TAP, td.nullCHOP), (VIDEO_TAP, td.nullTOP)):
        found = parent.op(name)
        if found is not None:
            found.destroy()
        null = startup.create(parent, optype, name)
        for connector in engine.outputConnectors:
            try:
                connector.connect(null)
            except Exception as error:
                lines.append(f"  {name} <- [{connector.index}] refused: {error}")
                continue
            if null.inputs:
                lines.append(f"  {name} <- [{connector.index}] connected")
                break
            lines.append(f"  {name} <- [{connector.index}] no error, not connected")
        else:
            lines.append(f"  {name}: no connector took it")
    startup.report("\n".join(lines))


def _values(chop, names):
    """name=value for each channel, or a line saying the CHOP is missing."""
    if chop is None:
        return "(missing)"
    parts = []
    for name in names:
        channel = chop[name]
        parts.append(f"{name}={'--' if channel is None else round(channel.eval(), 3)}")
    return " ".join(parts)


def status():
    """One report of the engine's state, its outputs and the host's frame rate."""
    import td

    parent = td.op(PARENT)
    engine = parent.op(ENGINE)
    lines = [
        f"{TAG} status",
        f"  engine   {_values(parent.op(STATUS_INFO), STATUS_CHANNELS)}",
        f"  perform  {_values(parent.op(PERFORM_INFO), PERFORM_CHANNELS)}",
        f"  host     {_values(parent.op(HOST_PERFORM), ('fps', 'msec', 'droppedframes'))}",
    ]
    if engine is not None:
        lines.append(f"  errors   {engine.errors()!r} warnings {engine.warnings()!r}")
    state = parent.op(STATE_TAP)
    lines.append(
        f"  state    {_values(state, STATE_CHANNELS)}" if state is not None
        else "  state    (no tap - run tap() after component_loaded)"
    )
    startup.report("\n".join(lines))


#: The last `rate()` sample, as (host perf_counter, engine_frame).
_RATE = {}


def rate():
    """The engine's real frame rate, measured between this call and the last.

    `engine_fps` off the Info CHOP read 58 while the engine was demonstrably
    running flat out, so it is not trustworthy as a rate. This counts the
    engine's own `absTime.frame` instead, over an interval it times itself -
    call it twice with any gap at all and the gap is measured rather than
    assumed. Nothing depends on the caller counting seconds.

    `perf_counter` rather than `monotonic`: on Windows the latter is
    GetTickCount64 at 15.625ms, which is a quarter of a frame at 60fps.
    """
    import td

    state = td.op(f"{PARENT}/{STATE_TAP}")
    if state is None:
        startup.report(f"{TAG} no {STATE_TAP} - run tap() first")
        return None
    channel = state["engine_frame"]
    if channel is None:
        startup.report(f"{TAG} no engine_frame on {state.path}")
        return None

    now, frame = time.perf_counter(), channel.eval()
    previous = _RATE.get("sample")
    _RATE["sample"] = (now, frame)
    if previous is None:
        startup.report(
            f"{TAG} rate: first sample at engine_frame {frame:.0f}"
            " - call rate() again whenever you like"
        )
        return None

    elapsed, advanced = now - previous[0], frame - previous[1]
    if elapsed <= 0:
        startup.report(f"{TAG} rate: no time between samples")
        return None
    measured = advanced / elapsed
    startup.report(
        f"{TAG} rate: engine advanced {advanced:.0f} frames in {elapsed:.2f}s"
        f" = {measured:.1f} fps"
    )
    return measured


def remove():
    """Destroy everything `setup()` made. The .tox and the log are kept."""
    import td

    parent = td.op(PARENT)
    for name in MADE:
        found = parent.op(name)
        if found is not None:
            found.destroy()
