"""Runtime controls — a rebuild button, made fresh on every launch.

Created by code on disk and never saved, so the `.toe` gains nothing from it:
the button exists while TouchDesigner is running and vanishes with the process.
That keeps the binary as disposable as it is without it.

Lives here rather than in `startup.py` for a practical reason: `reload()` can
reload this module and cannot reload that one, so the button can be iterated on
without restarting TouchDesigner.
"""

#: Where the controls go. Deliberately *beside* the build container, never
#: inside it: build() destroys and recreates its own container, so a button in
#: there would destroy itself in the middle of its own callback.
CONTROL_PARENT = "/project1"

BUTTON_NAME = "rebuild"
EXECUTE_NAME = "rebuild_exec"

#: Momentary: the value goes on while held and off on release, so a click is a
#: clean off-to-on edge rather than a state to be toggled back.
BUTTON_TYPE = "momentary"

#: Which panel value a click shows up as. If clicking does nothing, try
#: "select" - a button's momentary press is not always reported as "state".
PANEL_VALUE = "state"

#: The Panel Execute DAT's contents, written from here so the source of truth
#: stays on disk. It is a shim and nothing more: two lines into the package.
CALLBACK = '''# Generated by tdpy/controls.py — edits here are overwritten.


def onOffToOn(panelValue):
    import tdpy.startup

    tdpy.startup.reload()
    return
'''


def ensure_rebuild_button():
    """Create (or replace) the rebuild button and its callback DAT.

    Call this from startup, or by hand from the textport. **Not** from
    `reload()`: reload is what the button calls, and destroying the Panel
    Execute DAT while it is running its own callback is asking for trouble.
    """
    import td

    from . import startup

    parent = td.op(CONTROL_PARENT) or td.op("/")

    for name in (BUTTON_NAME, EXECUTE_NAME):
        existing = parent.op(name)
        if existing is not None:
            existing.destroy()

    # startup.create rather than parent.create: the latter appends a digit
    # rather than fail when it will not use a name, which is how this button
    # spent its first sessions at "rebuild1" while the code called it "rebuild".
    button = startup.create(parent, td.buttonCOMP, BUTTON_NAME)
    button.nodeX, button.nodeY = -250, 0
    # Two separate flags, and both are needed: `viewer` draws the panel on the
    # node, `activeViewer` makes that drawing respond to the mouse. With only
    # the first, the button looks right and does nothing.
    button.viewer = True
    button.activeViewer = True
    startup.set_par(button, "buttontype", BUTTON_TYPE)
    startup.set_par(button, "label", "rebuild")

    executor = startup.create(parent, td.panelexecuteDAT, EXECUTE_NAME)
    executor.nodeX, executor.nodeY = -250, -150
    executor.text = CALLBACK

    startup.set_par(executor, "panels", button.path)
    startup.set_par(executor, "panelvalue", PANEL_VALUE)
    startup.set_par(executor, "offtoon", True)
    startup.set_par(executor, "active", True)

    startup.report(f"[tdpy] rebuild button at {button.path}")
    return button
