"""The half of the project that runs inside the Engine COMP's process.

Phase 9 moves the player into a generated `.tox` run by an Engine COMP, in a
TouchDesigner process of its own. This module is both ends of that component's
life: `BOOTSTRAP` is the text of the one Execute DAT the host saves into the
`.tox`, and `main()` is what that DAT calls once the component has loaded.

**9.3 builds a trivial network only** - a Text TOP naming the engine's process
and frame, through the `program_video` output - to prove generate, save, load
and reload before anything real moves across. The player arrives at 9.4.

Four facts from the Phase 9 spikes shape the bootstrap, each on 330.0020:

- `onStart()` never runs under TouchEngine and `onCreate()` runs when the
  component loads, so the bootstrap uses `onCreate`.
- Inside the engine, `project.folder` and the working directory are the
  `.tox`'s folder, so the repository cannot be found from them. Its path is
  written into the bootstrap's text when the host generates it, since the host
  regenerates the `.tox` on every build and so the text is never older than the
  repository it names.
- Reloading keeps the engine process and its `sys.modules`, so the bootstrap
  drops the package before importing it - otherwise a reload after an edit
  would run the code that was loaded first.
- An exception raised inside the engine reaches the host as the Engine COMP's
  `errors()`, traceback included, so nothing here catches one.
"""

import os

#: The Execute DAT's text. Standard library only: it runs before the repository
#: is on `sys.path`, which is the first thing it puts there.
#:
#: The whole package goes, `tdpy` itself included, rather than the submodules
#: that `startup.reload()` drops. That function keeps `tdpy.startup` because it
#: is the module running, and so has to delete each submodule's attribute off
#: the surviving package too. Nothing here is part of the package, so dropping
#: the package takes those attributes with it.
BOOTSTRAP = '''# Generated by tdpy/build.py from tdpy/engine.py - edits here are overwritten.
import sys

REPO = __REPO__
PACKAGE = "tdpy"


def purge(modules, package):
    stale = [
        name for name in list(modules)
        if name == package or name.startswith(package + ".")
    ]
    for name in stale:
        del modules[name]
    return stale


def onCreate():
    if REPO not in sys.path:
        sys.path.insert(0, REPO)
    purge(sys.modules, PACKAGE)
    import tdpy.engine

    tdpy.engine.main(me.parent())
    return
'''

#: The Text TOP 9.3 puts through the program output.
PROBE_TOP = "probe"


def bootstrap_source(repo):
    """The bootstrap's text, with the repository's path written into it.

    `repr` rather than quotes around the string: the path has spaces in it
    today and backslashes on Windows, and a repr is a Python literal whatever
    the path contains.
    """
    return BOOTSTRAP.replace("__REPO__", repr(str(repo)))


def main(root):
    """Build the engine's network under `root`, the component's top level.

    Called by the bootstrap's `onCreate`, on every load and every reload. A
    reload brings the `.tox` back as it was saved, which is the bootstrap and
    the Out operators and nothing else, so each call starts from that - the
    probe is destroyed first only in case something calls this twice without
    a reload.

    Raises if the program output is missing, because that means the host
    generated the `.tox` wrongly, and a raise is what reaches the host.
    """
    import td

    from . import link, startup

    pid = os.getpid()
    name = link.output("program_video").name
    out = root.op(name)
    if out is None:
        raise LookupError(f"no {name} Out TOP in {root.path} - regenerate the .tox")

    previous = root.op(PROBE_TOP)
    if previous is not None:
        previous.destroy()
    probe = startup.create(root, td.textTOP, PROBE_TOP)
    probe.par.text.expr = f"'engine pid {pid}  frame ' + str(absTime.frame)"
    out.inputConnectors[0].connect(probe)

    startup.report(f"[engine pid {pid}] built {probe.path} into {out.path}")
    return probe
